### PR TITLE
Fixed docker-compose

### PR DESCRIPTION
**Pull request by ankitjain28may**

### CODE REVIEW

**Comment by dbjpanda** [comment]
Can you tell me what is its necessary ? Why are you sending NODE_CONTAINER_PORT as an env variable ?

**Comment by ankitjain28may** [comment]
@dbjpanda No it's not necessary, There is some error on my local. Closing this.

**Comment by dbjpanda** [comment]
Cool always feel free to comment whatever issue you are facing and anywhere. If we are free or may have knowledge on the issue we will leave our comments. That does not mean that we are stopping you to find the solution yourself.  It means even if you are facing an issue and if you comment or update us we will know that you are working or stuck somewhere. and sometimes we do some simple mistake and for that we spend a lot of times. So nothing is wrong if someone helps us out for simple solution. But you shouldn't depend on others.

**Comment by ankitjain28may** [comment]
Yes, Thanks :)

**Pull request closed without merging**
