### PR TITLE
Added Dockerfile

### PR DESCRIPTION
**Pull request by ankitjain28may**

### CODE REVIEW

**Comment by dbjpanda** [comment]
Getting below errors while building 
```
rm: cannot remove '/usr/share/doc/liblcms2-dev/LittleCMS2.6': No such file or directory
rm: cannot remove 'tutorial.pdf.gz': No such file or directory
rm: cannot remove '/usr/share/doc/liblcms2-dev/LittleCMS2.6': No such file or directory
rm: cannot remove 'Plugin': No such file or directory
rm: cannot remove 'API.pdf.gz': No such file or directory
rm: cannot remove '/usr/share/doc/liblcms2-dev/LittleCMS2.6': No such file or directory
rm: cannot remove 'API.pdf.gz': No such file or directory

```

**Comment by ankitjain28may** [comment]
@dbjpanda I am checking it

**Comment by ankitjain28may** [comment]
@dbjpanda I have fixed the error pls review.

**Comment by dbjpanda** [comment]
/app/node_modules/electron/install.js:47
  throw err
  ^
2018-07-02T17:44:11.666156000Z 
Error: Generated checksum for "electron-v1.8.7-linux-x64.zip" did not match expected checksum.
at ChecksumMismatchError.ErrorWithFilename (/app/node_modules/sumchecker/build.js:41:124)

**Comment by dbjpanda** [comment]
https://github.com/electron/electron/issues/9595#issuecomment-391693101

**Comment by ankitjain28may** [comment]
@dbjpanda Can you try to run again, I am not getting this error.

**Comment by dbjpanda** [comment]
@ankitjain28may To reproduce the issue first delete all the packages and then docker-compose up -d. It seems like there is an issue in "&" and "&&" .  As you have written `command: [sh, -c, "npm install & pm2-runtime process.json"]` . So before packages installed completely pm2-runtime gets executed. "&&" means if and only if command 1 completes successfully  then command 2 gets executed

**Comment by ankitjain28may** [comment]
@dbjpanda Thanks a lot, I will fix that in next PR :)

**Comment by dbjpanda** [comment]
@ankitjain28may Cool I have merged your PR and fixed that one :)

**Pull request merged**
