### PR TITLE
Added scraper node

### PR DESCRIPTION
**Pull request by ankitjain28may**

### CODE REVIEW

**Comment by shibasisp** [comment]
Looks good to me. Thanks!

**Comment by shibasisp** [comment]
capture the request object generated from drupal and post it here.

**Comment by ankitjain28may** [comment]
Request Header -

Host: localhost
User-Agent: Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:60.0) Gecko/20100101 Firefox/60.0
Accept: application/json, text/javascript, */*; q=0.01
Accept-Language: en-GB,en;q=0.5
Accept-Encoding: gzip, deflate
Referer: http://localhost/drupal/batch?id=533&op=start
X-Requested-With: XMLHttpRequest
Cookie: cookie value (I have removed)
Connection: keep-alive
Pragma: no-cache
Cache-Control: no-cache
Content-Length: 0

**Comment by ankitjain28may** [comment]
Request body - 

{ url:
   'https://www.amazon.in/s/ref=lp_14019572031_pg_2?rh=n%3A976389031%2Cn%3A%211318447031%2Cn%3A%211318449031%2Cn%3A14019572031&page=1&ie=UTF8&qid=1530099349',
  options:
   { context: 'li.s-result-item.celwidget',
     left_html: '',
     feeds_crawler: 1,
     no_of_pages: '2',
     delay: '0',
     url_pattern:
      'https://www.amazon.in/s/ref=lp_14019572031_pg_2?rh=n%3A976389031%2Cn%3A%211318447031%2Cn%3A%211318449031%2Cn%3A14019572031&page=$index&ie=UTF8&qid=1530099349',
     initial_value: '1',
     increment: '1',
     inner_feeds_scraper: 1,
     link_selector:
      'div.a-fixed-left-grid-col.a-col-right > div > div > a.a-link-normal.s-access-detail-page.s-color-twister-title-link.a-text-normal',
     base_url: '',
     inner_page_selector: '#dp-container',
     break_in_parts: 1,
     no_of_parts: '5' } }

**Comment by ankitjain28may** [comment]
left_html will have the value of remaining html that is left to process

**Comment by shibasisp** [comment]
LGTM Thanks! :+1:

**Comment by dbjpanda** [comment]
I tried to send a post request using postman with below data as raw(JSON) but I didn't get any output 
Am I missing something ? 

```
{
    "url": "https://www.amazon.in/s/ref=lp_14019572031_pg_2?rh=n%3A976389031%2Cn%3A%211318447031%2Cn%3A%211318449031%2Cn%3A14019572031&page=1&ie=UTF8&qid=1530099349",
    "options":{
            "context": "li.s-result-item.celwidget",
            "left_html": "",
            "feeds_crawler": 1,
            "no_of_pages": "2",
            "delay": "0",
            "url_pattern": "https://www.amazon.in/s/ref=lp_14019572031_pg_2?rh=n%3A976389031%2Cn%3A%211318447031%2Cn%3A%211318449031%2Cn%3A14019572031&page=$index&ie=UTF8&qid=1530099349",
            "initial_value": "1",
            "increment": "1",
            "inner_feeds_scraper": 1,
            "link_selector": "div.a-fixed-left-grid-col.a-col-right > div > div > a.a-link-normal.s-access-detail-page.s-color-twister-title-link.a-text-normal",
            "base_url": "",
            "inner_page_selector": "#dp-container",
            "break_in_parts": 1,
            "no_of_parts": "5"
    }
}
```
@ankitjain28may  Have you set up any authentication for the api ?

**Comment by ankitjain28may** [comment]
@dbjpanda  You made request to which route ?

**Comment by dbjpanda** [comment]
Just to update the issue incase any one wants to use the repo. 
I was trying to post to localhost:9000 instead of a proper url/route.

So there are two methods available till now. one is get-static to scrap content from a static site and get-dynamic to get data from dynamic sites. 

You need to post to something like localhost:9000/get-static with proper request object.

**Pull request merged**
